// Generated by Hive CE
// Do not modify
// Check in to version control

import 'package:hive_ce/hive.dart';
import 'package:hive_example/models/contactModel.dart';

extension HiveRegistrar on HiveInterface {
  void registerAdapters() {
    registerAdapter(contactModelAdapter());
  }
}
